.\"	$Id$
.\"
.\" Copyright (c) 2015 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: August 2 2015 $
.Dt KCGIREGRESS 3
.Os
.Sh NAME
.Nm kcgiregress ,
.Nm kcgi_regress_cgi ,
.Nm kcgi_regress_fcgi
.Nd regression framework for kcgi
.Sh LIBRARY
.Lb libkcgiregress
.Sh SYNOPSIS
.In kcgiregress.h
.Ft int
.Fo kcgi_regress_cgi
.Fa "int (*client)(void *)"
.Fa "void *clientData"
.Fa "int (*server)(void *)"
.Fa "void *serverData"
.Fc
.Ft int
.Fo kcgi_regress_fcgi
.Fa "int (*client)(void *)"
.Fa "void *clientData"
.Fa "int (*server)(void *)"
.Fa "void *serverData"
.Fc
.Sh DESCRIPTION
The
.Nm kcgi_regress_cgi
and
.Nm kcgi_regress_fcgi
functions are used for automated testing of
.Xr kcgi 3
systems, both as CGI and FastCGI scripts.
It is the mechanism used for internal regression tests as well.
.Pp
Applications wishing to use this framework provide callback functions to
.Fn kcgi_regress_cgi
and
.Fn kcgi_regress_fcgi ,
which invoke
.Fa server
with argument
.Fa serverArg
within a CGI or FastCGI environment as if it were spawned by a web
server, upon which the usual
.Xr khttp_parse 3
or
.Xr khttp_fcgi_init 3
and
.Xr khttp_fcgi_parse 3
functions are used to test behaviour.
Meanwhile, the
.Fa client
function is invoked for communicating with the server over port 17123.
The
.Xr libcurl 3
library is used for internal testing on the client side.
.Pp
In most applications, the main function invokes
.Nm kcgi_regress_cgi
or
.Nm kcgi_regress_fcgi ,
prepares a libCURL request in the client callback, then runs the usual
.Xr kcgi 3
sequence in the server callback.
.Sh RETURN VALUES
Both the
.Fa client
and
.Fa server
functions should return zero on test failure.
.Fn kcgi_regress_cgi
and
.Fn kcgi_regress_fcgi
return zero if any tests or internal machinery fail.
.Sh AUTHORS
The
.Nm kcgiregress
library was written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
