.\"	$Id$
.\"
.\" Copyright (c) 2020 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KHTML_ATTR 3
.Os
.Sh NAME
.Nm khtml_attr ,
.Nm khtml_attrx
.Nd open an element scope for kcgihtml
.Sh LIBRARY
.Lb libkcgihtml
.Sh SYNOPSIS
.In sys/types.h
.In stdarg.h
.In stdint.h
.In kcgi.h
.In kcgihtml.h
.Ft enum kcgi_err
.Fo khtml_attr
.Fa "struct khtmlreq *req"
.Fa "enum kelem elem"
.Fa "..."
.Fc
.Ft enum kcgi_err
.Fo khtml_attrx
.Fa "struct khtmlreq *req"
.Fa "enum kelem elem"
.Fa "..."
.Fc
.Sh DESCRIPTION
Open a new scope of element
.Fa elem
on the current element stack of
.Fa req ,
initialised with
.Xr khtml_open 3 .
Scopes are closed with
.Xr khtml_closeelem 3 ,
.Xr khtml_closeto 3 ,
or
.Xr khtml_close 3 .
If
.Fa elem
is a
.Qq void
eleemnt
.Pq self-closing, like Dv KELEM_LINK
or
.Dv KELEM_DOCTYPE ,
the scope is immediately closed so no new scope is opened.
.Pp
For
.Fn khtml_attr ,
variable arguments are in pairs, with the first of a pair being a
.Vt "enum attr"
of the attribute type and the second being a
.Pf non- Dv NULL
string.
.Pp
For
.Fn khtml_attrx ,
variable arguments are in triplets: the first is a
.Vt "enum attr"
of the attribute type, the second is a
.Vt "enum attrx"
describing the data format of the third type, and the third type is
either an
.Vt int64_t ,
.Vt char * ,
or
.Vt double
for
.Dv KATTRX_INT ,
.Dv KATTRX_STRING ,
or
.Dv KATTRX_DOUBLE ,
respectively.
.Pp
In both cases, string content is HTML escaped, for example, the
double-quote character is rendered as
.Qq &quot; .
This prevents arguments from
.Qq breaking
the attribute string context.
.Pp
The variable arguments terminated with a singular
.Dv KATTR__MAX .
.Sh RETURN VALUES
Returns an
.Ft enum kcgi_err
indicating the error state.
.Bl -tag -width -Ds
.It Dv KCGI_OK
Success (not an error).
.It Dv KCGI_ENOMEM
Internal memory allocation failure, including reaching the maximum
number of possible HTML scopes.
.It Dv KCGI_HUP
The output connection has been terminated.
For FastCGI connections, the current connection should be released with
.Xr khttp_free 3
and parse loop reentered.
.It Dv KCGI_FORM
The connection is still expecting headers with
.Xr khttp_head 3 .
Indicates that
.Xr khttp_body 3
did not return with success or was not invoked.
For FastCGI connections, the current connection should be released with
.Xr khttp_free 3
and parse loop reentered.
.It Dv KCGI_SYSTEM
Internal system error writing to the output stream.
.El
.Sh EXAMPLES
The following outputs a simple HTML page.
It assumes
.Va r
is a
.Vt struct kreq
pointer.
For brevity, it does not do any error checking.
.Bd -literal -offset indent
khttp_head(r, kresps[KRESP_STATUS],
  "%s", khttps[KHTTP_200]);
khttp_head(r, kresps[KRESP_CONTENT_TYPE],
  "%s", kmimetypes[KMIME_TEXT_HTML]);
khttp_body(r);
khtml_open(&req, r, 0);
khtml_elem(&req, KELEM_DOCTYPE);
khtml_elem(&req, KELEM_HTML);
khtml_elem(&req, KELEM_HEAD);
khtml_attr(req, KELEM_META,
  KATTR_CHARSET, "utf-8", KATTR__MAX);
khtml_attrx(req, KELEM_LINK,
  KATTR_REL, KATTRX_STRING, "stylesheet",
  KATTR_HREF, KATTRX_STRING, "style.css",
  KATTR__MAX);
khtml_close(&req);
.Ed
.Pp
The latter invocation could just as easily use
.Fn khtml_attr .
.Sh SEE ALSO
.Xr kcgihtml 3
.Sh AUTHORS
Written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
