.\"	$Id$
.\"
.\" Copyright (c) 2014 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 10 2016 $
.Dt KHTTP_FREE 3
.Os
.Sh NAME
.Nm khttp_free ,
.Nm khttp_child_free
.Nd free a CGI instance for kcgi
.Sh LIBRARY
.Lb libkcgi
.Sh SYNOPSIS
.In stdarg.h
.In stdint.h
.In unistd.h
.In kcgi.h
.Ft void
.Fo khttp_free
.Fa "struct kreq *req"
.Fc
.Ft void
.Fo khttp_child_free
.Fa "struct kreq *req"
.Fc
.Sh DESCRIPTION
The
.Nm khttp_free
and
.Nm khttp_child_free
functions free the resources of
.Fa req
allocated by
.Xr khttp_parse 3
or
.Xr khttp_fcgi_parse 3 ,
flushing the HTTP data stream in the process.
After calling this function, the members of
.Fa req
should not be used and the function should not be called again.
.Pp
The
.Nm khttp_child_free
performs the same operations as
.Nm khttp_free ,
but does not flush the HTTP data stream.
Thus, it may be used after invoking
.Xr fork 2
without confusing the output buffer.
.Sh SEE ALSO
.Xr kcgi 3 ,
.Xr khttp_parse 3
.Sh AUTHORS
The
.Nm khttp_free
and
.Nm khttp_child_free
functions were written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
