.\" Copyright (c) 2020 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KHTTP_EPOCH2DATETIME 3
.Os
.Sh NAME
.Nm khttp_epoch2datetime
.Nd convert time to components
.Sh LIBRARY
.Lb libkcgi
.Sh SYNOPSIS
.In sys/types.h
.In stdarg.h
.In stdint.h
.In kcgi.h
.Ft void
.Fo khttp_epoch2datetime
.Fa "int64_t epoch"
.Fa "int64_t *sec"
.Fa "int64_t *min"
.Fa "int64_t *hour"
.Fa "int64_t *mday"
.Fa "int64_t *mon"
.Fa "int64_t *year"
.Fa "int64_t *wday"
.Fa "int64_t *yday"
.Fc
.Sh DESCRIPTION
Format an
.Fa epoch
value
.Pq seconds since Jan 1, 1970, 00:00:00 UTC
into its broken-down time components.
The components are filled in as follows:
.Bl -column hourx aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -offset indent
.It Fa sec Ta seconds 0\(en59
.It Fa min Ta minutes 0\(en59
.It Fa hour Ta hours 0\(en23
.It Fa day Ta day of month 1\(en31
.It Fa mon Ta month 1\(en12
.It Fa year Ta year -2.9e11\(en2.9e11
.It Fa yday Ta day in year 0\(en365
.It Fa wday Ta day in week 0\(en6 (Sunday = 0)
.El
.Pp
If any of the pointers are
.Dv NULL ,
they are ignored.
.Pp
For broken-down time values suitable for
.Vt "struct tm" ,
see
.Xr khttp_epoch2tms 3 .
.Sh SEE ALSO
.Xr khttp_datetime2epoch 3 ,
.Xr khttp_epoch2str 3 ,
.Xr khttp_epoch2tms 3
.Sh AUTHORS
Written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
