.\"	$Id$
.\"
.\" Copyright (c) 2020 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KHTTP_EPOCH2DATETIME 3
.Os
.Sh NAME
.Nm khttp_epoch2datetime
.Nd convert time to components
.Sh LIBRARY
.Lb libkcgi
.Sh SYNOPSIS
.In sys/types.h
.In stdarg.h
.In stdint.h
.In kcgi.h
.Ft void
.Fo khttp_epoch2datetime
.Fa "int64_t epoch"
.Fa "int64_t *tm_sec"
.Fa "int64_t *tm_min"
.Fa "int64_t *tm_hour"
.Fa "int64_t *tm_mday"
.Fa "int64_t *tm_mon"
.Fa "int64_t *tm_year"
.Fa "int64_t *tm_wday"
.Fa "int64_t *tm_yday"
.Fc
.Sh DESCRIPTION
Format an
.Fa epoch
value
.Pq seconds since Jan 1, 1970, 00:00:00 UTC
into its broken-down time components.
The components are as follows:
.Pq Fa tm_sec ,
minutes 0\(en59
.Pq Fa tm_min ,
hours 0\(en23
.Pq Fa tm_hour ,
day of month 1\(en31
.Pq Fa tm_mday ,
month 0\(en11
.Pq Fa tm_mon ,
year minus 1900,
.Pq Fa tm_year ,
day of week with Sunday at 0
.Pq Fa tm_wday ,
and day of year 0\(en365
.Pq Fa tm_yday .
If any of the pointers are
.Dv NULL ,
they are ignored.
.Sh SEE ALSO
.Xr khttp_datetime2epoch 3 ,
.Xr khttp_epoch2str 3 ,
.Xr khttp_epoch2tms 3
.Sh AUTHORS
Written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
