.\"	$Id$
.\"
.\" Copyright (c) 2016--2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KUTIL_DATE2EPOCH 3
.Os
.Sh NAME
.Nm kutil_date2epoch ,
.Nm kutil_date_check ,
.Nm kutil_datetime2epoch ,
.Nm kutil_datetime_check
.Nd format and parse time for HTTP operations
.Sh LIBRARY
.Lb libkcgi
.Sh SYNOPSIS
.In sys/types.h
.In stdarg.h
.In stdint.h
.In kcgi.h
.Ft int64_t
.Fo kutil_date2epoch
.Fa "int64_t day"
.Fa "int64_t mon"
.Fa "int64_t year"
.Fc
.Ft int
.Fo kutil_date_check
.Fa "int64_t day"
.Fa "int64_t mon"
.Fa "int64_t year"
.Fc
.Ft int64_t
.Fo kutil_datetime2epoch
.Fa "int64_t day"
.Fa "int64_t mon"
.Fa "int64_t year"
.Fa "int64_t hour"
.Fa "int64_t min"
.Fa "int64_t sec"
.Fc
.Ft int
.Fo kutil_datetime_check
.Fa "int64_t day"
.Fa "int64_t mon"
.Fa "int64_t year"
.Fa "int64_t hour"
.Fa "int64_t min"
.Fa "int64_t sec"
.Fc
.Sh DESCRIPTION
The
.Fn kutil_date2epoch
function converts a day, month, and year into an epoch (at time 00:00:00).
It does no validation of the given values.
The
.Fn kutil_datetime2epoch
function is similar, but acts upon time values as well.
.Pp
The
.Fn kutil_date2epoch
and
.Fn kutil_datetime2epoch
functions have corresponding validation routines,
.Fn kutil_date_check
and
.Fn kutil_datetime_check ,
which return zero if their arguments do not describe valid dates and
times, and non-zero otherwise.
Dates are constrained to be within years 1582 and 9999.
.Pp
All of these date functions are designed to avoid how native
.Xr gmtime 3
and time formatting functions access time-zone files, which may
unwittingly crash given some operating system's sandbox mechanisms.
.Sh AUTHORS
These functions were written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
.Sh CAVEATS
The
.Vt time_t
and
.Vt "struct tm"
types are not used for the epoch to avoid expanding header requirements
for
.In kcgi.h
and because the
.Vt int64_t
type is used consistently for integral values.
