name: Regression Tests
on: [push]
jobs:
  linux_standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: configure
      run: ./configure
    - name: Compile
      run: bmake
    - name: Run regress
      run: bmake regress
  linux_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: configure
      run: ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
    - name: Compile
      run: bmake
    - name: Run regress
      run: bmake regress
  macos_standard:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: ./configure
    - name: Compile
      run: make
    - name: Run regress
      run:  make regress
