name: Regression Tests
on: [push]
jobs:
  ubuntu_standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure
    - name: Build and test
      run: bmake regress
  ubuntu_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
    - name: Build and test
      run: bmake regress
  ubuntu_libbsd_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake pkg-config libbsd-dev
    - name: Configure
      run: |
        cat /etc/os-release
        CFLAGS=$(pkg-config --cflags libbsd-overlay) ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1" LDFLAGS=$(pkg-config --libs libbsd-overlay)
    - name: Build and test
      run: bmake regress
  macos_standard:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: brew install bmake
    - name: Configure
      run: ./configure
    - name: Build and test
      run: bmake regress
  alpine_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Alpine Linux environment for x86_64
      uses: jirutka/setup-alpine@v1.1.4
      with:
        packages: >
          build-base
          curl-dev
          bmake
          zlib-dev
          linux-headers
        shell-name: alpine-x86_64.sh
    - name: Setup latest Alpine Linux for aarch64
      uses: jirutka/setup-alpine@v1.1.4
      with:
        arch: aarch64
        packages: >
          build-base
          curl-dev
          bmake
          zlib-dev
          linux-headers
        shell-name: alpine-aarch64.sh
    - name: Setup latest Alpine Linux for armv7
      uses: jirutka/setup-alpine@v1.1.4
      with:
        arch: armv7
        packages: >
          build-base
          curl-dev
          bmake
          zlib-dev
          linux-headers
        shell-name: alpine-armv7.sh
    - name: Setup latest Alpine Linux for ppc64le
      uses: jirutka/setup-alpine@v1.1.4
      with:
        arch: ppc64le
        packages: >
          build-base
          curl-dev
          bmake
          zlib-dev
          linux-headers
        shell-name: alpine-ppc64le.sh
    - name: Configure, build, and test on x86_64
      run: |
        cat /etc/alpine-release
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
        bmake regress
      shell: alpine-x86_64.sh {0}
    - name: Configure, build, and test on aarch64
      run: |
        cat /etc/alpine-release
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
        bmake regress
      shell: alpine-aarch64.sh {0}
    - name: Configure, build, and test on armv7
      run: |
        cat /etc/alpine-release
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
        bmake regress
      shell: alpine-armv7.sh {0}
    - name: Configure, build, and test on ppc64le
      run: |
        cat /etc/alpine-release
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
        bmake regress
      shell: alpine-ppc64le.sh {0}
