name: Regression Tests
on: [push]
jobs:
  linux_standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: configure
      run: ./configure
    - name: Compile
      run: bmake
    - name: Run regress
      run: bmake regress
  linux_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev bmake
    - name: configure
      run: ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
    - name: Compile
      run: bmake
    - name: Run regress
      run: bmake regress
  macos_standard:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: brew install bmake
    - name: configure
      run: ./configure
    - name: Compile
      run: bmake
    - name: Run regress
      run:  bmake regress
  alpine_sandboxed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Alpine Linux environment
      uses: jirutka/setup-alpine@v1.1.4
    - name: Install dependencies
      run: |
        cat /etc/alpine-release
        apk add build-base libcurl bmake
      shell: alpine.sh --root {0}
    - name: Compile and run regress
      run: |
        ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1"
        bmake
        bmake regress
      shell: alpine.sh {0}
